### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by bg55-a** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-bg55-a#1]
[Infografía Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-bg55-a/files/10746392/Infografia.Realidad.Aumentada.pdf)

**Comment by kirus21** [comment]
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
